server:
  port: ${SERVER_PORT:8088}

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: product-route
              uri: lb://product
              predicates:
                - Path=/product/**
              filters:
                - StripPrefix=1

            - id: cart-route
              uri: lb://cart
              predicates:
                - Path=/cart/**
              filters:
                - StripPrefix=1

            - id: sales-route
              uri: lb://sales
              predicates:
                - Path=/sales/**
              filters:
                - StripPrefix=1