server:
  port: ${SERVER_PORT:8088}

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-route
              uri: lb://product
              predicates:
                - Path=/product/**
              filters:
                - StripPrefix=1